// request item line with item line id 1 
GET https://localhost:5001/api/item_lines/1
API_KEY: f6g7h8i9j0
####

// request item line name from item line with id 1 
GET https://localhost:5001/api/item_lines/1/name
API_KEY: f6g7h8i9j0
####

// request item line description from item line with id 1 
GET https://localhost:5001/api/item_lines/1/description
API_KEY: f6g7h8i9j0
####

// request item line created at from item line with id 1 
GET https://localhost:5001/api/item_lines/1/created_at
API_KEY: f6g7h8i9j0
####

// faulty request 
GET https://localhost:5001/api/item_lines/1/created_at1
API_KEY: f6g7h8i9j0
####

// Update item line info 
PUT https://localhost:5001/api/item_lines/1
Content-Type: application/json
API_KEY: a1b2c3d4e5

{
  "name": "Home Appliances",
  "description": "test"
}
####
# Add a new item line
POST https://localhost:5001/api/item_lines
Content-Type: application/json
API_KEY: a1b2c3d4e5

{
  "id": 1,
  "name": "Appliances",
  "description": "Line for home and kitchen appliances"
}

####


DELETE https://localhost:5001/api/item_lines/1
Admin-Key: a1b2c3d4e5
ADMIN_KEY: a1b2c3d4e5