// request shipment with shipment id 1 
GET http://localhost:3000/api/v1/shipments/1
API_KEY: f6g7h8i9j0
####

// request shipment date from shipment with id 1 
GET http://localhost:3000/api/v1/shipments/1/shipment_date
API_KEY: f6g7h8i9j0
####

// request shipment notes from shipment with id 1 
GET http://localhost:3000/api/v1/shipments/1/notes
API_KEY: f6g7h8i9j0
####

// request shipment items from shipment with id 1 
GET http://localhost:3000/api/v1/shipments/1/items
API_KEY: f6g7h8i9j0
####

// faulty request 
GET http://localhost:3000/api/v1/shipments/1/items1
API_KEY: f6g7h8i9j0
####
# Add a new shipment
POST http://localhost:3000/api/v1/shipments
Content-Type: application/json
API_KEY: a1b2c3d4e5

{
  "id": 1,
  "order_id": 1,
  "source_id": 33,
  "order_date": "2000-03-09",
  "request_date": "2000-03-11",
  "shipment_date": "2000-03-13",
  "shipment_type": "I",
  "shipment_status": "Pending",
  "notes": "Zee vertrouwen klas rots heet lachen oneven begrijpen.",
  "carrier_code": "DPD",
  "carrier_description": "Dynamic Parcel Distribution",
  "service_code": "Fastest",
  "payment_type": "Manual",
  "transfer_mode": "Ground",
  "total_package_count": 31,
  "total_package_weight": 594.42,
  "items": [
    {
      "item_id": "P007435",
      "amount": 23
    },
    {
      "item_id": "P009557",
      "amount": 1
    },
    {
      "item_id": "P009553",
      "amount": 50
    }
  ]
}
