// request shipment with shipment id 1 
GET http://localhost:3000/api/v1/shipments/1
API_KEY: f6g7h8i9j0
####

// request shipment date from shipment with id 1 
GET http://localhost:3000/api/v1/shipments/1/shipment_date
API_KEY: f6g7h8i9j0
####

// request shipment notes from shipment with id 1 
GET http://localhost:3000/api/v1/shipments/1/notes
API_KEY: f6g7h8i9j0
####

// request shipment items from shipment with id 1 
GET http://localhost:3000/api/v1/shipments/1/items
API_KEY: f6g7h8i9j0
####

// faulty request 
GET http://localhost:3000/api/v1/shipments/1/items1
API_KEY: f6g7h8i9j0
####

// Update shipments info 
PUT http://localhost:3000/api/v1/shipments/1
Content-Type: application/json
API_KEY: a1b2c3d4e5

{
  "shipment_status": "Delivered",  
  "carrier_description": "Dynamic Parcel Distribution"
}
####