// request item type with item type id 1 
GET http://localhost:3000/api/v1/item_types/1
API_KEY: f6g7h8i9j0
####

// request item type name from item type with id 1 
GET http://localhost:3000/api/v1/item_types/1/name
API_KEY: f6g7h8i9j0
####

// request item type description from item type with id 1 
GET http://localhost:3000/api/v1/item_types/1/description
API_KEY: f6g7h8i9j0
####

// request item type created at from item type with id 1 
GET http://localhost:3000/api/v1/item_types/1/created_at
API_KEY: f6g7h8i9j0
####

// faulty request 
GET http://localhost:3000/api/v1/item_types/1/created_at1
API_KEY: f6g7h8i9j0
####

DELETE http://localhost:3000/api/v1/item_types/1
API_KEY: f6g7h8i9j0
ADMIN_KEY: a1b2c3d4e5
####