// request supplier with supplier id 1 
GET http://localhost:3000/api/v1/suppliers/1
API_KEY: f6g7h8i9j0
####

// request supplier name from supplier with id 1 
GET http://localhost:3000/api/v1/suppliers/1/name
API_KEY: f6g7h8i9j0
####

// request supplier address from supplier with id 1 
GET http://localhost:3000/api/v1/suppliers/1/address
API_KEY: f6g7h8i9j0
####

// request supplier created at from supplier with id 1 
GET http://localhost:3000/api/v1/suppliers/1/created_at
API_KEY: f6g7h8i9j0
####

// faulty request 
GET http://localhost:3000/api/v1/suppliers/1/created_at1
API_KEY: f6g7h8i9j0
####

// Update suppliers info 
PUT http://localhost:3000/api/v1/suppliers/1
Content-Type: application/json
API_KEY: a1b2c3d4e5

{
  "name": "Lee, Parks and Johnson",
  "address": "5989 Sullivan Drives"
}
####
####

DELETE http://localhost:3000/api/v1/suppliers/1
API_KEY: f6g7h8i9j0
ADMIN_KEY: a1b2c3d4e5
####