name: CargoHub Application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: CargoHubV2

    - name: Build Project
      run: dotnet build --no-restore
      working-directory: CargoHubV2

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests time

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Start CargoHub Web Application
      run: |
        dotnet run --project ./CargoHubV2/CargohubV2.csproj --urls http://0.0.0.0:5000 &
        sleep 10

    - name: Run Integration Tests
      run: pytest ./CargoHubTest/IntegrationTests
