name: CargoHub Application

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: CargoHubV2

    - name: Build Project
      run: dotnet build --no-restore
      working-directory: CargoHubV2

  UnitTests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Run Unit Tests
      run: dotnet test
      working-directory: CargoHubTest 
  
  IntegrationTests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
    
    - name: Start API
      run: |
        dotnet run &
        sleep 10
        curl http://localhost:5000/
      working-directory: CargoHubV2

    - name: Run Integratie Tests
      run: dotnet test
      working-directory: CargoHubV2