name: CargoHub Application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: CargoHubV2

    - name: Build Project
      run: dotnet build --no-restore
      working-directory: CargoHubV2

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Run Unit Tests
      run: dotnet test
      working-directory: CargoHubTest 
